// jest/vue_jest/src/pages/TodoList/TodoList.vue
<template>
  <div class="hello">
    <Header @add='addUndoItem'/>
    <UndoList :list='undoList' @delete="handleItemDelete" @status="changeStatus" @reset="resetStatus"/>
  </div>
</template>

<script>
import Header from '../../components/Header/Header'
import UndoList from '../../components/UndoList/UndoList'
import axios from 'axios'
export default {
  name: 'TodoList',
  components: {
    Header,
    UndoList
  },
  data () {
    return {
      undoList: []
    }
  },
  methods: {
    addUndoItem (inputValue) {
      this.undoList.push({ status: 'div', value: inputValue })
    },
    handleItemDelete (index) {
      this.undoList.splice(index, 1)
    },
    changeStatus (index) {
      this.undoList = this.undoList.map((item, i) => {
        if (i === index) {
          return { status: 'input', value: item.value }
        } else {
          return item
        }
      })
    },
    resetStatus () {
      this.undoList = this.undoList.map((item, i) => {
        return { status: 'div', value: item.value }
      })
    }
  },
  mounted () {
    /*
    * {
    *   success: true,
    *   data: [{
    *     status: 'div',
    *     value: 'dell lee'
    *   }]
    * }
    * */
    axios.get('/getUndoList.json').then((res) => {
      this.undoList = res.data
    }).catch(e => {
      console.log(e)
    })
    // setTimeout(() => {
    //   axios.get('/getUndoList.json').then((res) => {
    //     this.undoList = res.data
    //   }).catch(e => {
    //     console.log(e)
    //   })
    // }, 5000)
  }
}
</script>

<style scoped lang="scss">

</style>

// jest/react_jest/src/container/TodoList/TodoList.jsx
import React, { useState, useEffect } from 'react'
import Header from './components/Header/Header'
import UndoList from './components/UndoList/UndoList'
import axios from 'axios'
import './style.css'

const TodoList = () => {

  const [undoList, setUndoList] = useState([])

  const addUndoItem = (item) => {
    const newUndoList = [...undoList, { status: 'div', value: item }]
    setUndoList(newUndoList)
  }

  useEffect( () => {
    // {
    //   data: [{
    //     status: 'div',
    //     value: 'dell lee'
    //   }],
    //     success: true
    // }
    const setList = async () => {
      try {
        const result = await axios.get('/undoList.json')
        setUndoList(result.data)
      } catch(e) {
        console.log(e)
      }
    }
    setList()
    // const I = setTimeout(() => {
    //   setList()
    // }, 5000)
    // return () => {clearTimeout(I)}
  }, [])

  const changeStatus = (index) => {
    const newList = undoList.map((item, i) => {
      if (index === i) {
        return {
          ...item,
          status: 'input'
        }
      } else {
        return {
          ...item,
          status: 'div'
        }
      }
    } )
    setUndoList(newList)
  }

  const handleBlur = (index) => {
    const newList = undoList.map((item, i) => {
      if (index === i) {
        return {
          ...item,
          status: 'div'
        }
      } else {
        return {
          ...item
        }
      }
    } )
    setUndoList(newList)
  }

  return (
    <div>
      <Header addUndoItem={addUndoItem}/>
      <UndoList
        list={undoList}
        setUndoList={setUndoList}
        changeStatus={changeStatus}
        handleBlur={handleBlur}
      />
    </div>
  )
}

export default TodoList
